#!/bin/bash
# Smart Allotment Node Install Script
# Run as the smartallotment user

set -e

# Always run from script directory (repo root)
cd "$(dirname "$0")"

echo "=== Smart Allotment Node Installer ==="
echo "====================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# --- Detect OS & Hardware ---
echo -e "${YELLOW}🔎 Detecting system...${NC}"

IS_PI=false
if grep -q "Raspberry Pi" /proc/device-tree/model 2>/dev/null; then
  IS_PI=true
  echo -e "${GREEN}✅ Raspberry Pi detected${NC}"
else
  echo -e "${YELLOW}⚠️  Raspberry Pi NOT detected (dev/test mode)${NC}"
fi

OS_NAME=$(lsb_release -ds 2>/dev/null || uname -a)
echo "🖥️  OS: $OS_NAME"
echo ""

# --- 1. Prompt user for configuration ---
read -p "Enter DEVICE_ID for this Pi (e.g., SA-NODE1): " DEVICE_ID
read -p "Enter MQTT broker host/IP (e.g., 192.168.0.114): " MQTT_HOST
read -p "Enter MQTT broker port [1883]: " MQTT_PORT
MQTT_PORT=${MQTT_PORT:-1883}

read -p "Enter MQTT username (leave empty if none): " MQTT_USERNAME
read -s -p "Enter MQTT password (leave empty if none): " MQTT_PASSWORD
echo ""

# --- 2. Raspberry Pi system dependencies ---
if [ "$IS_PI" = true ]; then
  echo -e "${YELLOW}🔧 Installing Raspberry Pi system dependencies...${NC}"

  sudo apt update
  sudo apt install -y \
    python3-full \
    python3-dev \
    python3-pip \
    python3-smbus \
    i2c-tools \
    git

  echo -e "${YELLOW}🔌 Enabling I2C interface...${NC}"
  if ! grep -q "^dtparam=i2c_arm=on" /boot/config.txt 2>/dev/null; then
    sudo sed -i 's/^#dtparam=i2c_arm=on/dtparam=i2c_arm=on/' /boot/config.txt || true
    echo "dtparam=i2c_arm=on" | sudo tee -a /boot/config.txt
    echo -e "${YELLOW}⚠️  I2C enabled — reboot required after install!${NC}"
  else
    echo -e "${GREEN}✅ I2C already enabled${NC}"
  fi

  echo -e "${YELLOW}🔍 Scanning I2C bus...${NC}"
  i2cdetect -y 1 || true
else
  echo -e "${YELLOW}ℹ️  Skipping Raspberry Pi specific setup${NC}"
fi

# --- 3. Prepare Node directory ---
NODE_DIR=/opt/smart_allotment_node
echo -e "${YELLOW}📁 Preparing $NODE_DIR...${NC}"

sudo mkdir -p "$NODE_DIR"
sudo chown "$USER:$USER" "$NODE_DIR"
cd "$NODE_DIR"

# --- 4. Clone or update repo ---
if [ -d ".git" ]; then
  echo -e "${YELLOW}🔄 Updating existing Node repository...${NC}"
  git pull origin main
else
  echo -e "${YELLOW}📥 Cloning Node repository...${NC}"
  git clone git@github.com:Gev1990123/smart_allotment_node.git .
fi

# --- 5. Create Python virtual environment ---
if [ ! -d "venv" ]; then
  echo -e "${YELLOW}🐍 Creating Python virtual environment...${NC}"
  python3 -m venv venv
fi

source venv/bin/activate

# --- 6. Install Python dependencies ---
echo -e "${YELLOW}📦 Installing Python dependencies...${NC}"
pip install --upgrade pip
pip install -r requirements.txt

# --- 7. Create .env file ---
echo -e "${YELLOW}📝 Creating .env file...${NC}"

cat > "$NODE_DIR/.env" <<EOL
# Auto-generated by install_node.sh

DEVICE_ID=$DEVICE_ID

MQTT_HOST=$MQTT_HOST
MQTT_PORT=$MQTT_PORT
MQTT_USERNAME=$MQTT_USERNAME
MQTT_PASSWORD=$MQTT_PASSWORD

PUBLISH_INTERVAL=30
EOL

chmod 600 "$NODE_DIR/.env"

echo -e "${GREEN}✅ .env file created at $NODE_DIR/.env${NC}"

# --- 8. Create systemd service ---
SERVICE_FILE=/etc/systemd/system/smart-allotment-node.service
echo -e "${YELLOW}⚙️  Creating systemd service...${NC}"

sudo bash -c "cat > $SERVICE_FILE" <<EOL
[Unit]
Description=Smart Allotment MQTT Node
After=network.target

[Service]
User=$USER
Group=$USER
WorkingDirectory=$NODE_DIR
ExecStart=$NODE_DIR/venv/bin/python $NODE_DIR/main.py
Restart=always
RestartSec=5
EnvironmentFile=$NODE_DIR/.env

[Install]
WantedBy=multi-user.target
EOL

# --- 9. Enable and start service ---
echo -e "${YELLOW}🚀 Enabling and starting service...${NC}"

sudo systemctl daemon-reload
sudo systemctl enable smart-allotment-node
sudo systemctl restart smart-allotment-node

# --- 10. Final status ---
echo ""
echo -e "${GREEN}🎉 Smart Allotment Node installed successfully!${NC}"
echo ""
echo "📍 Node ID:        $DEVICE_ID"
echo "📡 MQTT Broker:   $MQTT_HOST:$MQTT_PORT"
echo "🖥️  OS:            $OS_NAME"
echo "🍓 Raspberry Pi:  $IS_PI"
echo ""
echo "🔎 Check logs with:"
echo "   journalctl -u smart-allotment-node -f"
echo ""
if [ "$IS_PI" = true ]; then
  echo -e "${YELLOW}⚠️  If this is first install and I2C was enabled, REBOOT NOW:${NC}"
  echo "   sudo reboot"
fi
